spring.application.name=flytrack-api

# Datasource PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flytrackdb}
spring.datasource.username=${DB_USER:flytrack}
spring.datasource.password=${DB_PASS:flytrack123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Ejecutar data.sql con datos iniciales despues de que Hibernate crea las tablas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Puerto del servidor
server.port=8080

# CORS permitido para el frontend Angular
spring.web.cors.allowed-origins=http://localhost:4200
